### PR TITLE
#15 Fix remaining warnings

### LINKED ISSUE #15: Fix last warnings from Go Report
To get a perfect report, the following issues have to be fixed:
- cyclomatic complexity in [agentimpl/message.go](https://github.com/crucibuild/sdk-agent-go/blob/master/agentimpl/message.go#L149): ```warning: cyclomatic complexity 20 of function (*AMQP).Connect() is high (> 15) (gocyclo)```
- 3 mispells in [agentiface/message.go](https://github.com/crucibuild/sdk-agent-go/blob/master/agentiface/message.go): ```warning: "occuring" is a misspelling of "occurring" (misspell)```

Doing this will remove all the remaining warnings from Go Report.

### PR DESCRIPTION
**Pull request by ccamel**
This closes #15 and will enable us to reach 100% for the [Go Report](https://goreportcard.com/report/github.com/crucibuild/sdk-agent-go).

### CODE REVIEW

**Comment by ccamel** [comment]
Argh ! By refactoring the code and creating 2 additional functions, the code coverage has slightly decreased. That's too unfair. :sob:

**Comment by jpigree** [comment]
I had the same thing did to me in the last PR. So unfair. Honestly, you can merge this. We will add up many tests soon enough.

**Comment by jpigree** [comment]
ouargh. The diff on the message method is difficult to follow. As I understand it, it is just split though. So I will grant you the approval.

**Review by jpigree — APPROVED** [review]
Well Done!

**Comment by ccamel** [comment]
Thanks for the agreement. :smiley:

**Pull request merged**
