### PR TITLE
 #17 Hook gometalinter into the CI.

### PR DESCRIPTION
**Pull request by jpigree**
Implemented it into a script because writing Makefiles is painful.

### CODE REVIEW

**Comment by jpigree** [comment]
I created the PR but we have new warnings to fix. :P

**Comment by ccamel** [comment]
commit 5b9ef8d in the branch should fix the last remaining warnings of [gometalinter](https://github.com/alecthomas/gometalinter), provided that following checks are disabled:
- [lll](https://github.com/walle/lll): as we have agreed, the length of the lines is not a concern.
- [dupl](https://github.com/mibk/dupl): the tool shows code duplications which in my opinion are not really founded, and particularly inappropriate to fix. I therefore suggest to disable this check.
- [goimports](https://godoc.org/golang.org/x/tools/cmd/goimports): the tool reports false warnings regarding the nature of the project. As we are coding an sdk, it is legitimate to have packages that are not imported. So I suggest to disable this check.

**Review by ccamel — APPROVED** [review]
That's fine to me. Good job ! :+1:

**Comment by jpigree** [comment]
Travis have a bug which prevents nproc to see the correct number of cpus allocated.
=> https://github.com/travis-ci/travis-ci/issues/6859
Until this is fixed, we will use the -j2 for linting.

**Pull request merged**
