### PR TITLE
#19 use a Manifest for agents creation

### PR DESCRIPTION
**Pull request by ccamel**
Here is a minimal improvement which addresses #19. There's a room for others improvements, but currently, it does the job.

As the fix breaks the interface for the agents that use this sdk, we should not delay too much the PR.

### CODE REVIEW

**Comment by ccamel** [comment]
Argh, CI has failed:

```
gometalinter -j2 --config "/home/travis/gopath/src/github.com/crucibuild/sdk-agent-go/gometalinter.json" ./...
WARNING: deadline exceeded by linter safesql (try increasing --deadline)
make: *** [check] Error 2
The command "make ci" exited with 2.
Done. Your build exited with 1.
```

**Comment by jpigree** [comment]
Okay it is gometalinter. It seems "-j2" fix was not enough.

**Comment by jpigree** [comment]
I will adress this tomorrow and I will review this PR in the process.

**Comment by ccamel** [comment]
From what I see, we can deal with the issue by doing so:
- increase the duration of the deadline (option `--deadline` of `gometalinter`), which is set to 30s by default;
- remove the linter `safesql` which has no value in our case. This should make the build faster.

What is your opinion on it ?

**Comment by jpigree** [comment]
I think doing both would be great. :)

**Comment by ccamel** [comment]
Great, let's do it. :slightly_smiling_face:

**Review by jpigree — APPROVED** [review]
Okay, globally you used composition over inheritance. I can't disagree with that.

**Pull request merged**
